# Generated by Django 3.2.3 on 2022-04-23 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Avail'), ('B', 'Booked'), ('R', 'Running'), ('U', 'Unconditioned')], default='A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/pics')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=10)),
                ('lincense', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('actual_return_time', models.DateTimeField()),
                ('ride_cost', models.IntegerField()),
                ('fine_cost', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.bike')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bike_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('location', models.ManyToManyField(to='bike_rental_app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.location'),
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike_rental_app.bike_model'),
        ),
    ]
