# Generated by Django 3.2.3 on 2022-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='drop_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='pick_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
