# Generated by Django 3.2.3 on 2022-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental_app', '0002_auto_20220423_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='drop_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='pick_time',
            field=models.DateTimeField(),
        ),
    ]
