# Generated by Django 3.2.3 on 2022-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental_app', '0003_auto_20220423_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/bike_models'),
        ),
    ]
